batch_size: 512
dataset_subdir: Panda-Data
debug: false
device: cuda
diffusion_model_class: GaussianDiffusionModel
git_hash: 92e65846201c891bcc5e3640f2a2d87ffe96e474
git_url: https://github.com/XuehuaOvO/cart_pole_diffusion_based_on_MPD.git
include_velocity: false
loss_class: GaussianDiffusionCartPoleLoss
lr: 0.003
model_saving_address: /root/cartpoleDiff/cart_pole_diffusion_based_on_MPD/trained_models/panda_test6_117600
n_diffusion_steps: 25
num_train_steps: 114843.75
predict_epsilon: true
results_dir: ./logs/train_diffusion_Panda_2024-12-19_10-50-31/dataset_subdir___Panda-Data/include_velocity___False/use_ema___True/variance_schedule___exponential/n_diffusion_steps___25/predict_epsilon___True/unet_dim_mults_option___0/0
seed: 0
steps_til_ckpt: 10000
steps_til_summary: 2000
summary_class: SummaryTrajectoryGeneration
unet_dim_mults_option: 0
unet_input_dim: 32
use_amp: false
use_ema: true
variance_schedule: exponential
wandb_entity: scoreplan
wandb_group: Panda-Data-False-True-exponential-25-True-0
wandb_mode: disabled
wandb_project: train_diffusion_Panda
