batch_size: 512
dataset_subdir: CartPole-NMPC
debug: false
device: cuda
diffusion_model_class: GaussianDiffusionModel
git_hash: 662c79f701451c1c714ea77b0cdc73cf1effe236
git_url: https://github.com/XuehuaOvO/cart_pole_diffusion_based_on_MPD.git
include_velocity: false
loss_class: GaussianDiffusionCartPoleLoss
lr: 0.003
model_saving_address: /root/cartpoleDiff/cart_pole_diffusion_based_on_MPD/trained_models/cart_pole_84000_test1
n_diffusion_steps: 25
num_train_steps: 82031.25
predict_epsilon: true
results_dir: ./logs/train_diffusion_CartPole_2025-01-03_15-17-01/dataset_subdir___CartPole-NMPC/include_velocity___False/use_ema___True/variance_schedule___exponential/n_diffusion_steps___25/predict_epsilon___True/unet_dim_mults_option___0/0
seed: 0
steps_til_ckpt: 10000
steps_til_summary: 2000
summary_class: SummaryTrajectoryGeneration
unet_dim_mults_option: 0
unet_input_dim: 32
use_amp: false
use_ema: true
variance_schedule: exponential
wandb_entity: scoreplan
wandb_group: CartPole-NMPC-False-True-exponential-25-True-0
wandb_mode: disabled
wandb_project: train_diffusion_CartPole
